# Copyright 2016 The Web BSD Hunt Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################
#
# TODO: High-level file comment.
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets

- url: /index.html
  static_files: client/hunt.html
  upload: client/hunt.html

- url: /hunt.js
  static_files: client/hunt.js
  upload: client/hunt.js

- url: /
  static_files: client/hunt.html
  upload: client/hunt.html

- url: /api/v1/.*
  script: _go_app

#
# SERVER_GAME_URL can contain a special template instruction, "{{instance}}".  If there are multiple
# game servers, {{instance}} will be replaced with a specific one, or "0" if the frontend doesn't know
# the ids of any instances.
#
env_variables:
  SERVER_KEEPALIVE_TOPIC: 'keepalive'
  SERVER_GAME_URL: 'https://{{instance}}-dot-server-game-dot-webhunt-dev.appspot.com/jsonrpc'
  SERVER_GAME_RPC:  'jsonrpc'
  SERVER_FRONTEND_STANDALONE: 'no'
# SERVER_FRONTEND_RPROXY_OPTIONS:'RPROXY_LOG_REQUEST_HEADERS,RPROXY_LOG_RESPONSE_HEADERS,RPROXY_LOG_ERROR,RPROXY_LOG_SUCCESS,RPROXY_LOG_PROXY_REQUEST,RPROXY_LOG_PROXY_HEADERS,RPROXY_DISABLE_REDIRECT'
